#!/usr/bin/env bash

if [ "$1" == "release" ]; then
    version="$2"
    gitext tag v$version
    brew create https://github.com/tungse1209/xcode-ci/archive/v$version.tar.gz
    brew_file_path="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xcode-ci.rb"
    copyshavalue -ps $brew_file_path -pd ./../homebrew-xcode-ci/xcode-ci.rb
    rm -rf $brew_file_path
    chmod +x xcode-ci
    current_path=$(pwd)
    gitext push "release $version"
    cd ./../homebrew-xcode-ci
    gitext push "release $version"
    cd $current_path
fi
if [ "$1" == "reinstall" ]; then
    brew_formula="$2"
    brew uninstall --force $brew_formula
    brew install $brew_formula
    chmod +x /usr/local/opt/$brew_formula/bin/$brew_formula
    brew audit --new-formula $brew_formula
fi